{{- if and .Values.auth.createAdmin (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.admin-secret" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
data:
  {{ include "miniflux.admin-secret-username-key" . | quote }}: {{ .Values.auth.adminUsername | b64enc | quote }}
  {{ include "miniflux.admin-secret-password-key" . | quote }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}
