{{- if and .Values.auth.oauth2.enabled (not .Values.auth.oauth2.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.oauth-secret" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
data:
  {{ include "miniflux.oauth-secret-client-id-key" . | quote }}: {{ required "client id is required when no existing secret is provided. Please set auth.oauth2.clientId or auth.oauth2.existingSecret" .Values.auth.oauth2.clientId | b64enc | quote }}
  {{ include "miniflux.oauth-secret-client-secret-key" . | quote }}: {{ required "client secret is required when no existing secret is provided. Please set auth.oauth2.clientSecret or auth.oauth2.existingSecret" .Values.auth.oauth2.clientSecret | b64enc | quote }}
{{- end }}
