{{- if and .Values.auth.createAdmin (not .Values.auth.existingSecret) -}}
{{- $username := required "A valid admin username is required when admin user creation is enabled. Please set auth.adminUsername" .Values.auth.adminUsername }}
{{- $password := required "A valid admin password is required when admin user creation is enabled. Please set auth.adminPassword" .Values.auth.adminPassword }}
{{- $passwordLength := len $password -}}
{{- if lt $passwordLength 6 }}
{{- fail (printf "admin password must be at least 6 characters. Current password only has %s" ($passwordLength | plural "one character" (printf "%s characters" ($passwordLength | toString)))) -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miniflux.admin-secret" . }}
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
data:
  {{ include "miniflux.admin-secret-username-key" . | quote }}: {{ .Values.auth.adminUsername | b64enc | quote }}
  {{ include "miniflux.admin-secret-password-key" . | quote }}: {{ .Values.auth.adminPassword | b64enc | quote }}
{{- end }}
