{{- if .Values.auth.createAdmin -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "miniflux.fullname" . }}-create-admin-user"
  labels:
    {{- include "miniflux.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    metadata:
      name: "{{ include "miniflux.fullname" . }}-create-admin-user"
      labels:
        {{- include "miniflux.labels" . | nindent 8}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "miniflux.postgresql.wait-init-container" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-create-admin-user
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "miniflux.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: [ "miniflux" ]
          args: [ "-create-admin" ]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretName" .Subcharts.postgresql }}
                  key: {{ include "postgresql.userPasswordKey" .Subcharts.postgresql }}
            - name: DATABASE_URL
              value: {{ include "miniflux.postgresql.connection-url" . }}
            {{- if .Values.debug }}
            - name: DEBUG
              value: "1"
            {{- end }}
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "miniflux.admin-secret" . }}
                  key: {{ .Values.auth.secretKeys.username }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "miniflux.admin-secret" . }}
                  key: {{ .Values.auth.secretKeys.password }}
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
